name: Node package

on:

  workflow_dispatch:
    inputs:
      qase_api_base_url:
        description: 'Qase API URL'
        required: true
      qase_report:
        description: 'Enabled/disabled reporting to Qase'
        required: true
      qase_project_code:
        description: 'Qase project code'
        required: true
      qase_run_id:
        description: 'Qase Run ID'
        required: true
      qase_run_complete:
        description: 'Complete Qase Run'
        required: true

env:
  QASE_API_BASE_URL: ${{ inputs.qase_api_base_url }}
  QASE_REPORT: ${{ inputs.qase_report }}
  QASE_PROJECT_CODE: ${{ inputs.qase_project_code }}
  QASE_RUN_ID: ${{ inputs.qase_run_id }}
  QASE_RUN_COMPLETE: ${{ inputs.qase_run_complete }}
  QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
  
       push:
          paths-ignore:
        - 'examples/**'
  
jobs:
   build-php:
    runs-on: ubuntu-latest
    steps:
      - uses: qase-tms/qase-link-run@main
        env:
          QASE_API_TOKEN: ${{ env.QASE_API_TOKEN }}
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        node-version: [ '14', '15', '16' ]
        prefix: [ "qaseio", "qase-cypress", "qase-cucumberjs", "qase-newman", "qase-testcafe", "qase-jest", "qase-playwright" ]
    name: Project ${{ matrix.prefix }} - Node ${{ matrix.node-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - working-directory: ./${{ matrix.prefix }}
      run: npm install
    - working-directory: ./${{ matrix.prefix }}
      run: npm run lint
    - working-directory: ./${{ matrix.prefix }}
      run: npm run test
  build-n-publish:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      max-parallel: 5
      matrix:
        prefix: [ "qaseio", "qase-cypress", "qase-cucumberjs", "qase-newman", "qase-testcafe", "qase-jest", "qase-playwright" ]
    if: startsWith(github.event.ref, 'refs/tags')
    name: Publish ${{ matrix.prefix }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      if: contains(github.event.ref, matrix.prefix)
      with:
        node-version: '14'
        registry-url: 'https://registry.npmjs.org'
    - if: contains(github.event.ref, matrix.prefix)
      working-directory: ./${{ matrix.prefix }}
      run: npm install
    - if: contains(github.event.ref, matrix.prefix)
      working-directory: ./${{ matrix.prefix }}
      run: npm run build
    - if: contains(github.event.ref, matrix.prefix)
      working-directory: ./${{ matrix.prefix }}
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
